[package]
name = "rust-releases"
version = "0.10.0"
authors = ["Martijn Gribnau <garm@ilumeo.com>"]
description = "Index and access all available Rust releases"
license = "MIT OR Apache-2.0"
edition = "2018"

documentation = "https://docs.rs/rust-releases"
repository = "https://github.com/foresterre/rust-releases"

[features]
default = ["aws_index"]
# Dependencies requires to download the S3 index
aws_index = ["rusoto_core", "rusoto_s3", "tokio"]

# internal feature: enable download test, which is heavily rate limitted
dl_test = []

[dependencies]
# error handling
thiserror = "1.0.23"

# caching, fetching, etc.
attohttpc = "0.16.1"
directories-next = "2.0.0"

rusoto_core = { version = "0.46.0", optional = true }
rusoto_s3 = { version = "0.46.0", optional = true }
tokio = { version = "1", optional = true }

# parsing manifests
semver = "0.11"
serde = { version = "1", features = ["derive"] }
toml = "0.5"
regex = "1.4.5"
lazy_static = "1.4.0"

[dev-dependencies]
yare = "1.0.0"