[package]
name = "rust-releases-rust-dist"
version = "0.15.1"
authors = ["Martijn Gribnau <garm@ilumeo.com>"]
edition = "2018"
description = "RustDist source implementation for rust-releases"
license = "MIT OR Apache-2.0"

documentation = "https://docs.rs/rust-releases-rust-dist"
repository = "https://github.com/foresterre/rust-releases"

[dependencies]
rust-releases-core = { version = "0.15.1", path = "../rust-releases-core" }
rust-releases-io = { version = "0.15.1", path = "../rust-releases-io" }

thiserror = "1.0.24"

lazy_static = "1.4.0"
rusoto_core = { version = "0.46.0" }
rusoto_s3 = { version = "0.47.0" }
regex = "1.4.5"
tokio = { version = "1" }
